name: PHP Chapter workflow

on:
  push:
    branches: [ "main" ]
jobs:
    checks:
      runs-on: ubuntu-latest
      container: lukavavetic/php-chapter-1
      steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout Repo Action
        uses: actions/checkout@v2
        
      - name: Run Composer update
        run: composer update

      - name: Run PHP Lint
        run: vendor/bin/phplint

      - name: Run PHP tests
        run: vendor/bin/phpunit

      - name: Run PHP Stan
        run: vendor/bin/phpstan analyse
    
    docker-image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Docker Login
          env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
          run: docker login -u $DOCKER_USER -p $DOCKER_SECRET
          
        - name: Docker Image Build
          run: docker image build -t lukavavetic/php-chapter-1 .
          
        - name: Docker Image Push
          run: docker image push lukavavetic/php-chapter-1
        
